GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2luYSIsImlhdCI6MTY1NTI4NzExNiwiZXhwIjoxNjU1Mjg3MTQ2fQ.D7VcYo78uPfH2JV0za_CpRSrpFhRu2RRbNT-RfWEj6o

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username":"Gina"
}